# A debugging utility for testing Minio from within k8s.
apiVersion: v1
kind: Pod
metadata:
  name: deis-slugbuilder
  labels:
    heritage: deis
    version: 2.0.0-beta
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/slugbuilder:v2-beta
      env:
        - name: DEBUG
          value: "1"
        - name: TAR_URL
          value: "https://s3.amazonaws.com/mytar/mytar.tgz"
        - name : put_url
          value: "https://s3-us-west-1.amazonaws.com/myslug/tmp"
      volumeMounts:
        - name: minio-user
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: minio-user
      secret:
        secretName: minio-user
